spring:
  redis:
    host: 192.168.2.128
server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        http-only: true
        domain: localhost
        path: /
        max-age:
          seconds: 1800