spring:
  application:
    name: user-eureka-client
server:
  port: 9003
  servlet:
    context-path: /eureka/client
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    com.microservice.demo.config: debug